version: "3.9"

services:
  pwani_app:
    build:
      context: .
      dockerfile: dockerfile   # your Dockerfile
    container_name: pwaniContentGeneration
    ports:
      - "8000:8000"            # map container port to host
    volumes:
                # mount project folder for live reload
      - ./logs:/app/logs       # mount logs folder
      - ./.env:/app/.env 
      - ./data_bases:/app/data_bases  # mount your .env file
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
